package com.pfem2.iso27004.Service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.pfem2.iso27004.Entity.ConstructTemplate;
import com.pfem2.iso27004.Repository.ConstructTemplateRepository;

@Component
public class DataInitializer implements CommandLineRunner {

    private final ConstructTemplateRepository constructTemplateRepository;

    @Autowired
    public DataInitializer(ConstructTemplateRepository constructTemplateRepository) {
        this.constructTemplateRepository = constructTemplateRepository;
    }

    @Override
    public void run(String... args) {
        seedAnnexBConstructs();
    }

    private void seedAnnexBConstructs() {
        List<ConstructTemplate> templates = List.of(
            ConstructTemplate.builder()
                .constructId("B.1.1")
                .name("ISMS-Trained Personnel")
                .controlReference("A.7.2.2")
                .controlObjective("Ensure all employees receive ISMS awareness and training")
                .objectOfMeasurement("Personnel training records")
                .attribute("Percentage of personnel trained in ISMS")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of personnel who have completed ISMS training")
                .derivedMeasureDescription("(Trained personnel / Total personnel) * 100")
                .measurementFunction("Ratio of trained staff to total staff expressed as percentage")
                .analyticalModel("If >= target, ISMS training programme is effective")
                .targetValue(90.0)
                .acceptableValue(75.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("quarterly")
                .indicatorInterpretation("Higher values indicate better ISMS training coverage")
                .infoOwner("HR Manager")
                .category("Human Resources Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.1.2")
                .name("Information Security Training")
                .controlReference("A.7.2.2")
                .controlObjective("Ensure all users receive relevant IS training")
                .objectOfMeasurement("IS training completion records")
                .attribute("Percentage of users completing IS training within required period")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of users completing IS training on schedule")
                .derivedMeasureDescription("(On-schedule completions / Required completions) * 100")
                .measurementFunction("Training compliance rate")
                .analyticalModel("Below acceptable threshold triggers mandatory re-training initiative")
                .targetValue(95.0)
                .acceptableValue(80.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("annually")
                .indicatorInterpretation("Measures timeliness and coverage of IS training programme")
                .infoOwner("Security Awareness Manager")
                .category("Human Resources Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.1.3")
                .name("IS Awareness Compliance")
                .controlReference("A.7.2.2")
                .controlObjective("Maintain high IS awareness across the organisation")
                .objectOfMeasurement("Awareness assessment results")
                .attribute("Average score on IS awareness assessment")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Sum of all individual awareness assessment scores")
                .derivedMeasureDescription("Average score = Sum of scores / Number of assessments")
                .measurementFunction("Arithmetic mean of assessment scores")
                .analyticalModel("Scores below acceptable trigger targeted awareness campaigns")
                .targetValue(80.0)
                .acceptableValue(65.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("annually")
                .indicatorInterpretation("Average score reflects overall IS awareness level")
                .infoOwner("Security Awareness Manager")
                .category("Human Resources Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.2.1")
                .name("Password Quality — Manual")
                .controlReference("A.9.3.1")
                .controlObjective("Ensure users select strong passwords")
                .objectOfMeasurement("Password audit results")
                .attribute("Percentage of audited passwords meeting policy requirements")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of passwords meeting complexity policy")
                .derivedMeasureDescription("(Compliant passwords / Total audited) * 100")
                .measurementFunction("Password compliance rate from manual audit sample")
                .analyticalModel("Non-compliant rate above threshold triggers policy enforcement review")
                .targetValue(98.0)
                .acceptableValue(90.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("quarterly")
                .indicatorInterpretation("High compliance indicates users follow password policy")
                .infoOwner("IT Security Officer")
                .category("Access Control")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.2.2")
                .name("Password Quality — Automated")
                .controlReference("A.9.3.1")
                .controlObjective("Enforce strong passwords through technical controls")
                .objectOfMeasurement("Authentication system logs")
                .attribute("Percentage of accounts with policy-compliant passwords (automated check)")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of accounts passing automated password strength check")
                .derivedMeasureDescription("(Passing accounts / Total accounts) * 100")
                .measurementFunction("Automated compliance rate from directory/IAM system")
                .analyticalModel("Non-compliance triggers automatic password reset enforcement")
                .targetValue(100.0)
                .acceptableValue(95.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("monthly")
                .indicatorInterpretation("Near-100% expected with technical enforcement in place")
                .infoOwner("IT Security Officer")
                .category("Access Control")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.3")
                .name("ISMS Review Process")
                .controlReference("A.6.1.1")
                .controlObjective("Ensure ISMS is reviewed at planned intervals")
                .objectOfMeasurement("ISMS review meeting records")
                .attribute("Number of ISMS reviews conducted on schedule")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Count of ISMS reviews completed as scheduled")
                .derivedMeasureDescription("(Completed reviews / Planned reviews) * 100")
                .measurementFunction("Review completion rate over measurement period")
                .analyticalModel("Rate below target indicates governance process weakness")
                .targetValue(100.0)
                .acceptableValue(80.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("annually")
                .indicatorInterpretation("100% indicates all planned ISMS reviews were conducted")
                .infoOwner("ISMS Manager")
                .category("Information Security Governance")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.4.1")
                .name("Incident Management Effectiveness")
                .controlReference("A.16.1.6")
                .controlObjective("Ensure IS incidents are resolved within acceptable timeframes")
                .objectOfMeasurement("Incident management system records")
                .attribute("Average time to resolve IS incidents (hours)")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Total hours to resolve all incidents in period")
                .derivedMeasureDescription("Total resolution hours / Number of incidents")
                .measurementFunction("Mean time to resolution (MTTR)")
                .analyticalModel("Lower MTTR indicates more effective incident response")
                .targetValue(4.0)
                .acceptableValue(24.0)
                .valueUnit("hours")
                .performance("desc")
                .frequency("monthly")
                .indicatorInterpretation("Lower values are better; above acceptable threshold requires process review")
                .infoOwner("Incident Response Manager")
                .category("Information Security Incident Management")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.4.2")
                .name("Corrective Action Implementation")
                .controlReference("A.16.1.6")
                .controlObjective("Ensure corrective actions from incidents are implemented timely")
                .objectOfMeasurement("Corrective action tracking system")
                .attribute("Percentage of corrective actions implemented on time")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of corrective actions closed by due date")
                .derivedMeasureDescription("(On-time closures / Total due) * 100")
                .measurementFunction("Corrective action closure rate")
                .analyticalModel("Low rate indicates systemic resource or process issues")
                .targetValue(90.0)
                .acceptableValue(70.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("monthly")
                .indicatorInterpretation("Higher values indicate corrective actions are followed through")
                .infoOwner("Incident Response Manager")
                .category("Information Security Incident Management")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.5")
                .name("Management Commitment to ISMS")
                .controlReference("A.6.1.1")
                .controlObjective("Ensure management actively supports the ISMS")
                .objectOfMeasurement("Management review records, resource allocation logs")
                .attribute("Percentage of management ISMS commitments fulfilled")
                .measurementMethodType("SUBJECTIVE")
                .scaleType("ORDINAL")
                .baseMeasureDescription("Count of management ISMS commitments fulfilled in period")
                .derivedMeasureDescription("(Fulfilled commitments / Total commitments) * 100")
                .measurementFunction("Commitment fulfilment rate")
                .analyticalModel("Low fulfilment signals governance risk requiring board escalation")
                .targetValue(90.0)
                .acceptableValue(70.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("quarterly")
                .indicatorInterpretation("Measures leadership's active engagement with ISMS responsibilities")
                .infoOwner("CISO")
                .category("Information Security Governance")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.6")
                .name("Protection Against Malicious Code")
                .controlReference("A.12.2.1")
                .controlObjective("Ensure all endpoints are protected against malicious software")
                .objectOfMeasurement("Endpoint management system")
                .attribute("Percentage of endpoints with up-to-date anti-malware protection")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of endpoints with current anti-malware signatures")
                .derivedMeasureDescription("(Protected endpoints / Total endpoints) * 100")
                .measurementFunction("Anti-malware coverage and currency rate")
                .analyticalModel("Below acceptable threshold requires immediate remediation sweep")
                .targetValue(99.0)
                .acceptableValue(95.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("monthly")
                .indicatorInterpretation("Near-100% required; gaps indicate unprotected attack surface")
                .infoOwner("IT Operations Manager")
                .category("Operations Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.7")
                .name("Physical Entry Controls")
                .controlReference("A.11.1.2")
                .controlObjective("Ensure secure areas are protected by appropriate entry controls")
                .objectOfMeasurement("Physical access control logs and audit records")
                .attribute("Percentage of secure area entry events that are authorised")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of authorised entry events to secure areas")
                .derivedMeasureDescription("(Authorised entries / Total entries) * 100")
                .measurementFunction("Authorised access rate from access control system")
                .analyticalModel("Unauthorised entries above threshold trigger physical security review")
                .targetValue(100.0)
                .acceptableValue(99.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("monthly")
                .indicatorInterpretation("Any unauthorised access is a significant security event")
                .infoOwner("Facilities Security Manager")
                .category("Physical and Environmental Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.8")
                .name("Log Files Review")
                .controlReference("A.12.4.1")
                .controlObjective("Ensure activity logs are reviewed regularly to detect anomalies")
                .objectOfMeasurement("Log review completion records")
                .attribute("Percentage of required log reviews completed on schedule")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of log review tasks completed as scheduled")
                .derivedMeasureDescription("(Completed reviews / Scheduled reviews) * 100")
                .measurementFunction("Log review completion rate")
                .analyticalModel("Incomplete log reviews increase risk of undetected security events")
                .targetValue(100.0)
                .acceptableValue(90.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("monthly")
                .indicatorInterpretation("High completion rate indicates proactive threat monitoring")
                .infoOwner("Security Operations Manager")
                .category("Operations Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.9")
                .name("Management of Periodic Maintenance")
                .controlReference("A.11.2.4")
                .controlObjective("Ensure equipment is maintained to ensure availability and integrity")
                .objectOfMeasurement("Maintenance management system records")
                .attribute("Percentage of scheduled maintenance tasks completed on time")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of maintenance tasks completed by scheduled date")
                .derivedMeasureDescription("(On-time completions / Total scheduled) * 100")
                .measurementFunction("Maintenance schedule adherence rate")
                .analyticalModel("Overdue maintenance increases equipment failure and availability risk")
                .targetValue(95.0)
                .acceptableValue(80.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("quarterly")
                .indicatorInterpretation("High adherence indicates well-managed infrastructure maintenance")
                .infoOwner("IT Operations Manager")
                .category("Physical and Environmental Security")
                .build(),

            ConstructTemplate.builder()
                .constructId("B.10")
                .name("Security in Third Party Agreements")
                .controlReference("A.15.1.2")
                .controlObjective("Ensure IS requirements are addressed in third party agreements")
                .objectOfMeasurement("Supplier contract review records")
                .attribute("Percentage of third party agreements containing required IS clauses")
                .measurementMethodType("OBJECTIVE")
                .scaleType("RATIO")
                .baseMeasureDescription("Number of third party agreements with complete IS security clauses")
                .derivedMeasureDescription("(Compliant agreements / Total active agreements) * 100")
                .measurementFunction("IS clause coverage rate across supplier contracts")
                .analyticalModel("Non-compliant agreements represent unmanaged supply chain risk")
                .targetValue(100.0)
                .acceptableValue(90.0)
                .valueUnit("%")
                .performance("asc")
                .frequency("annually")
                .indicatorInterpretation("100% required for full supplier IS assurance coverage")
                .infoOwner("Procurement Manager")
                .category("Supplier Relationships")
                .build()
        );

        for (ConstructTemplate template : templates) {
            if (!constructTemplateRepository.existsByConstructId(template.getConstructId())) {
                constructTemplateRepository.save(template);
            }
        }
    }
}
